// <auto-generated />
using Demos.HomeWork.ModelsDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demos.HomeWork.Migrations
{
    [DbContext(typeof(URDbContext))]
    [Migration("20230604185551_Vertion1")]
    partial class Vertion1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Demos.HomeWork.ModelsDb.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("_Roles");
                });

            modelBuilder.Entity("Demos.HomeWork.ModelsDb.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("_Users");
                });

            modelBuilder.Entity("RolesUsers", b =>
                {
                    b.Property<int>("rolesListId")
                        .HasColumnType("int");

                    b.Property<int>("usersListId")
                        .HasColumnType("int");

                    b.HasKey("rolesListId", "usersListId");

                    b.HasIndex("usersListId");

                    b.ToTable("RolesUsers");
                });

            modelBuilder.Entity("RolesUsers", b =>
                {
                    b.HasOne("Demos.HomeWork.ModelsDb.Roles", null)
                        .WithMany()
                        .HasForeignKey("rolesListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Demos.HomeWork.ModelsDb.Users", null)
                        .WithMany()
                        .HasForeignKey("usersListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
